<div class="p-4">
    <form action="<?php echo BASE_URL . 'actualizar-pais/' . $country->id ?>" method="POST" class="d-flex justify-content-center p-4">
        <div class="card" style="width: 60%; padding: 30px;">
            <h5 class="card-title text-center">Modificar País</h5>      

            <div class="mb-3">
                <label for="name" class="form-label">Nombre</label>
                <input class="form-control" type="text" maxlength="50" name="name" value="<?php echo $country->name ?>" required>
            </div>

            <div class="mb-3">
                <label for="currency" class="form-label">Moneda</label>
                <input class="form-control" maxlength="50" name="currency" value="<?php echo $country->currency ?>" required>
            </div>
                  
            <div class="mb-3">
                <label for="language" class="form-label">Idioma</label>
                <input required class="form-control" maxlength="50" value="<?php echo $country->language ?>" name="language">
            </div>

            <input type="hidden" name="id" value="<?php echo $country->id; ?>">
            <div class="form-text mb-3">*Todos los datos deben estar completos para modificar el país*</div>

            <div class="text-center">
                <button type="submit" class="btn btn-danger">Modificar</button>
                <a href="<?php echo BASE_URL . 'paises'; ?>" class="btn btn-secondary ms-2">Cancelar</a>
            </div>
        </div>
    </form>
</div>
