<form action="<?php echo BASE_URL . 'crear-atraccion/' ?>" method="POST" enctype="multipart/form-data" class="d-flex justify-content-center p-4">
    <div class="card" style="width: 60%; padding: 30px;">
        <h5 class="card-title text-center">Agregar Nueva Atracción</h5>

        <div class="mb-3">
            <label for="path_img" class="form-label">Imagen</label>
            <input class="form-control" type="file" accept=".png, .jpg, .jpeg" name="path_img">
        </div>

        <div class="mb-3">
            <label for="name" class="form-label">Nombre</label>
            <input class="form-control" type="text" name="name" required>
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Descripción</label>
            <textarea class="form-control" name="description" rows="3" required></textarea>
        </div>

        <label for="schedules" class="form-label">Horarios</label>
        <div class="mb-3 d-flex align-items-center">
            <input required class="form-control me-2" type="time" name="open_time" placeholder="Hora de apertura">
            <span>-</span>
            <input required class="form-control ms-2" type="time" name="close_time" placeholder="Hora de cierre">
        </div>

        <div class="mb-3">
            <label for="price" class="form-label">Precio</label>
            <input required class="form-control" type="number" min="0" step="0.1" name="price" value="0.00">
        </div>

        <div class="mb-3">
            <label for="location" class="form-label">Dirección</label>
            <input required class="form-control" type="text" name="location">
        </div>

        <div class="mb-3">
            <label for="website" class="form-label">Página Oficial</label>
            <input required class="form-control" type="url" name="website">
        </div>

        <label for="country_id" class="form-label">País</label>
        <select name="country_id" class="form-select" required>
            <?php if (!empty($countries)): ?>
                <?php foreach ($countries as $country): ?>
                    <option value="<?php echo $country->id; ?>">
                        <?php echo htmlspecialchars($country->name); ?>
                    </option>
                <?php endforeach; ?>
            <?php else: ?>
                <option value="">No hay países disponibles</option>
            <?php endif; ?>
        </select>

        <div class="form-text mb-3">*Todos los datos deben estar completos para agregar la atracción*</div>

        <div class="text-center">
            <button type="submit" class="btn btn-danger">Agregar</button>
            <a href="<?php echo BASE_URL . 'atracciones'; ?>" class="btn btn-secondary ms-2">Cancelar</a>
        </div>
    </div>
</form>
