<div class="card-body" style=" display:flex; justify-content:center; padding:50px">
  <div class="card" style="width: 50%; padding:30px;">
    <form method="POST" action="<?php echo BASE_URL . 'autenticar'?>">

      <?php if (isset($message) && !empty($message)): ?>
        <div class="alert alert-danger" role="alert">
          <?php echo htmlspecialchars($message, ENT_QUOTES, 'UTF-8'); ?>
        </div>
      <?php endif; ?>

      <div class="mb-3">
        <label for="username" class="form-label">Usuario </label>
        <input type="text" class="form-control" name="username" required>
        <div class="form-text">Vamos a compartir este nombre de usuario con todo el mundo</div>
      </div>
      
      <div class="mb-3">
        <label for="password" class="form-label">Contraseña</label>
        <input type="password" class="form-control" name="password" required>
      </div>
      
      <button type="submit" class="btn btn-danger">Ingresar</button>

    </form>
  </div>
</div>
