<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error 404 - Página No Encontrada</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="error-container">
        <h1>Error</h1>
        <h2>Lo sentimos, <?php echo ($error) ?></h2>
        <a href="<?php echo BASE_URL .'atracciones'?>" >Volver al inicio</a>
    </div>
</body>
</html>