<footer>
  <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.wirelesseducation.org%2Fwp-content%2Fuploads%2F2016%2F03%2Ffooter.png&f=1&nofb=1&ipt=8139fc2448e6d043145c3cb962506190d0c97184014a891abb04b718199bd26f&ipo=images" style="height:150px; width:100%;padding:0;">
  <div class="d-flex flex-wrap justify-content-center align-items-center  p-3 m-0" style="background: linear-gradient(to right, #0091ae, #0ea282, #87bb3c); width:100%;">
    <div class="align-items-center">
      <span class="text-muted"> TUDAI 2024 - GRUPO 43 - Florencia Alarcos - Adrian Wilgenhoff </span>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</footer>