<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TUDAI Viaja</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #47CACC;">
  <div class="container-fluid">
    <a class="navbar-brand" href="<?php echo BASE_URL . 'atracciones' ?>" > 🏔️ viajarr.com</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown" style="justify-content: end;">
      <ul class="navbar-nav" >
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<?php echo BASE_URL . 'atracciones' ?>">Home</a>
        </li>    
        <?php if (isset($_SESSION['USER_ID'])) :?>     
        <li class="nav-item ">
          <a class="nav-link " href="<?php echo BASE_URL . 'paises' ?>">
            Paises *
          </a>
          <?php endif ?>
        </li>
        <li class="nav-item">
		<?php if (!isset($_SESSION['USER_ID'])) :?>
          <a class="btn btn-outline-danger" aria-current="page" href="<?php echo BASE_URL . 'iniciar-sesion' ?>">Log In</a>
		  <?php else :?>
		  <a class="btn btn-outline-danger" aria-current="page" href="<?php echo BASE_URL . 'cerrar-sesion' ?>">Log Out</a>
		  <?php endif ?>
        </li>   
      </ul>
    </div>
  </div>
</nav>
    
</body>
</html>
