<div class="p-4 d-flex justify-content-between">
    <div class="dropdown d-flex justify-content-between align-items-center">
        Filtrar por país:
        <button class="btn btn-danger dropdown-toggle ms-2" type="button" data-bs-toggle="dropdown">
            <?php echo htmlspecialchars($selectedCountry); ?>
        </button>
        <ul class="dropdown-menu">
            <li><a href="<?php echo BASE_URL . 'atracciones'; ?>" class="dropdown-item">Todos</a></li>
            <?php foreach ($countries as $country): ?>
                <li>
                    <a href="<?php echo BASE_URL . 'atracciones-por-pais/' . $country->name; ?>" class="dropdown-item">
                        <?php echo htmlspecialchars($country->name); ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="d-flex align-items-center me-n3" style="padding:20px; margin-right: -20px;">
        <?php if (isset($_SESSION['USER_ID'])) : ?>
            <a href="<?php echo BASE_URL . 'nueva-atraccion' ?>" type="button" class="btn btn-danger" style="margin-top:-20px;">Agregar</a>
        <?php endif ?>
    </div>
</div>
